### ISSUE TITLE
error: no matching function for call to 'text::font_height()'

### ISSUE THREAD

**Issue by ElephantHunters** [lakshanthad/Wio_Terminal_Classroom_Arduino#1]
In function 'void loop()':
sketch_sep24c:29:36: error: no matching function for call to 'text::font_height()'
 header.height(header.font_height() * 2); //height of title header

I received this error while working on the code present in this link
https://wiki.seeedstudio.com/Wio-Terminal-LCD-Linecharts/

**Comment by lakshanthad** [comment]
Hello @ElephantHunters,

Please refer to this code and try again.
https://github.com/Seeed-Studio/Seeed_Arduino_Linechart/blob/master/examples/basic_spr/basic_spr.ino

I will update the wiki in the meantime.

**Comment by lakshanthad** [comment]
Hello @ElephantHunters,

Please let me know whether the code I shared before in the previous comment worked. I will close this issue if everything is good.

**Comment by ElephantHunters** [comment]
> Hello @ElephantHunters,
> 
> Please let me know whether the code I shared before in the previous comment worked. I will close this issue if everything is good.

thank you for your response, please go ahead and close this issue
